spring.application.name=SalesSlavyApp

server.port=8181

spring.datasource.url=jdbc:mysql://localhost:3306/salesslavyapp
spring.datasource.username=root
spring.datasource.password=******
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.hibernate.ddl-auto=validate
jwt.secret=your-secrete-key
jwt.expiration=3600000

razorpay.key_id=rzp_test_LqWBBDbgwot5lh
razorpay.key_secret=NETk6HP1NzRzufOYZ7KYfDMb
