spring.application.name=SalesSlavyApp

server.port=8181

spring.datasource.url=jdbc:mysql://localhost:3306/salesslavyapp
spring.datasource.username=root
spring.datasource.password=Ratankumar@27
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.hibernate.ddl-auto=validate
jwt.secret=this-is-a-app-that-works-on-spring-web-and-e-commas-27030408754mugudnswhimscxksnxiojiojapox
jwt.expiration=3600000

razorpay.key_id=rzp_test_LqWBBDbgwot5lh
razorpay.key_secret=NETk6HP1NzRzufOYZ7KYfDMb
